# Generated by Django 3.2.3 on 2021-06-22 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('isbn', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='isbnlibro')),
                ('nombrelibro', models.CharField(max_length=20, verbose_name='Nombre libro')),
                ('autor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Autor')),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
